/-
LeaTTa: a machine-checked operational semantics and metatheory of MeTTa in Lean 4.
Book root (Verso manual genre). Built with `lake exe docs`.
-/
import VersoManual
import Illuminate
import Docs.Cd

import Docs.Papers
import Docs.ObjectLanguage
import Docs.Interpreter
import Docs.TypeSystem
import Docs.Metatheory
import Docs.Operational
import Docs.Correspondence
import Docs.Blockchain
import Docs.FutureWork
import Docs.Discussion

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Illuminate

open Docs

set_option pp.rawOnError true
set_option verso.code.warnLineLength 100

#doc (Manual) "LeaTTa: A Machine-Checked Operational Semantics and Metatheory of MeTTa in Lean 4" =>
%%%
authors := ["The LeaTTa Project"]
shortTitle := "LeaTTa"
%%%

:::paragraph
*Alpha.* This is an early, alpha-stage release and a starting foundation. It will be improved
substantially in upcoming iterations as MeTTa is more fully formalised. It currently formalises
Hyperon Experimental's minimal interpreter and standard library. It does *not* yet cover the
semantics of MeTTa-IL, the MeTTa intermediate language, which is still in development. Future
iterations are planned to add MeTTa-IL and MeTTa on Rholang.
:::

{index}[LeaTTa]
*LeaTTa* is a formalization, in the {citet lean4}[] interactive theorem prover, of the *MeTTa*
language at the heart of OpenCog Hyperon {citep goertzelMetagraph}[]. It covers:

 * the minimal interpreter;
 * the standard library;
 * the gradual type system;
 * a body of machine-checked *metatheory*: determinism, confluence of the deterministic fragment,
   type soundness, gradual-typing consistency, soundness *and* completeness of first-argument
   indexing, and a bisimulation connecting the running interpreter to the published operational
   semantics of MeTTa {citep mops}[].

Every theorem in this book is checked by Lean's kernel. The development contains *no* `sorry`,
`admit`, `native_decide`, `partial`, or `unsafe`; `#print axioms` reports only the three standard
classical axioms of Mathlib {citep mathlib}[], and the gradual-typing non-transitivity result depends
on no axioms at all. The executable interpreter is validated against Hyperon's own test corpus
(270/270 assertions).

:::paragraph
LeaTTa addresses two audiences:

 * *MeTTa/Hyperon developers*, as an independent, executable *specification* of the language.
   The MeTTa operational-semantics paper {citep mops}[] envisions exactly this role, a
   "JVM-specification" of MeTTa against which implementations can be judged compliant.
 * *Programming-language researchers*, as a worked formalization in the gradual-typing line of work
   begun by {citet siekTaha}[], in the tradition of mechanized language metatheory.
:::

# Why Formalize MeTTa? Blockchain, AGI, and Verifiable Semantics
%%%
tag := "sec-why"
%%%

MeTTa is headed for use as an *on-chain / smart-contract* language. In that setting a contract's
behaviour must be *predictable, replayable, and auditable*, and an optimised on-chain evaluator must
be provably faithful to the published semantics. A machine-checked metatheory can establish exactly
those properties. That is what drives LeaTTa's emphasis:

 * *Determinism / replayability*: the abstract machine is a single-valued function; all
   non-determinism is reified in an explicit result list, never in the transition relation.
 * *Type soundness*: a well-typed program is never rejected with a spurious error, and a reported
   type error is faithful (never fabricated).
 * *Auditability*: the knowledge base (contract state) is mutated *only* by explicit, attributable
   `add-atom`/`remove-atom`; pure reduction never changes it.
 * *Gas*: a resource-bounded variant in which energy is provably never created.
 * *Optimisation-faithfulness*: first-argument indexing computes exactly the published
   semantics' result set.

# A Note on This Document

A complete API reference, every definition and theorem with its docstring, is generated by doc-gen4
and hosted alongside this book at [the API reference](api/index.html).

This book is generated by Verso, the documentation system of the Lean language. Code blocks written
in Lean are elaborated by the same compiler that checks the development; for example, the following
is checked as you read it:

```lean
example : 1 + 1 = 2 := rfl
```

Diagrams are generated by Lean as well. The central result of {ref "sec-why"}[this chapter], that the
optimised interpreter and the published specification reduce a term to the *same* answers, is the
commuting square below, drawn here as a preview and proved in the correspondence chapter:

```diagram (cssWidth := "24em")
cd do
  let a ← CDM.node "t" cdBlue
  let b ← CDM.node "t" cdGreen
  let a' ← CDM.node "results" cdBlue
  let b' ← CDM.node "results" cdGreen
  CDM.grid #[#[some a, some a'], #[some b, some b']]
  CDM.arrow a a' (some "kernel") cdBlue .above
  CDM.arrow b b' (some "MOPS") cdGreen .below
  CDM.arrow a b (some "=") cdInk .left
  CDM.arrow a' b' (some "=") cdInk .right
```

The remaining chapters cover the object language, the minimal interpreter and its standard
library, the gradual type system, the metatheory, the operational semantics and its correspondence to
the interpreter, the blockchain-oriented guarantees, the `future-work` branch, and a discussion
of the development's current limitations and open problems.

{include 1 Docs.ObjectLanguage}

{include 1 Docs.Interpreter}

{include 1 Docs.TypeSystem}

{include 1 Docs.Metatheory}

{include 1 Docs.Operational}

{include 1 Docs.Correspondence}

{include 1 Docs.Blockchain}

{include 1 Docs.FutureWork}

{include 1 Docs.Discussion}
